# infra/k8s/service.yml
apiVersion: v1
kind: Service
metadata:
  name: credit-risk-api
  namespace: credit-risk
  labels:
    app.kubernetes.io/name: credit-risk-api
    app.kubernetes.io/part-of: credit-risk-xai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: credit-risk-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
